# Generated by Django 3.2.6 on 2021-08-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_name', models.CharField(choices=[('TM', 'Flax - Todi Mills'), ('P', 'Flax - Powai'), ('B', 'Flax - Bandra')], max_length=2)),
                ('order_date', models.DateField()),
                ('super_category', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('net_sell', models.FloatField(default=0)),
                ('food_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.fooditem')),
            ],
        ),
    ]
