# Generated by Django 3.2.6 on 2021-08-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_posdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posdata',
            options={'verbose_name_plural': 'POS Data List'},
        ),
        migrations.RemoveField(
            model_name='posdata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='posdata',
            name='super_category',
        ),
    ]
