# Generated by Django 3.2.6 on 2021-08-30 11:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20210829_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ('item_number', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='posdata',
            options={'ordering': ('food_item__item_number', 'order_date', 'outlet_name'), 'verbose_name_plural': 'POS Data List'},
        ),
        migrations.AddField(
            model_name='posdata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='POSIngredientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('TM', 'Flax - Todi Mills'), ('P', 'Flax - Powai'), ('B', 'Flax - Bandra')], max_length=2)),
                ('order_date', models.DateField()),
                ('quantity', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.ingredient')),
            ],
            options={
                'verbose_name_plural': 'POS Ingredient Data List',
                'ordering': ('order_date', 'store', 'ingredient__pk'),
            },
        ),
    ]
